// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpw5XEHcSPF-dvPMReaWksq69QPa6mrRA',
    appId: '1:34606072539:web:54ff0841a6a831ff62c2fe',
    messagingSenderId: '34606072539',
    projectId: 'astico-app',
    authDomain: 'astico-app.firebaseapp.com',
    storageBucket: 'astico-app.firebasestorage.app',
    measurementId: 'G-0X08NX5L3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwverN4QNJoqykF2XXlFc9-SdRhoFi2w',
    appId: '1:34606072539:android:aa3b27575a958b4e62c2fe',
    messagingSenderId: '34606072539',
    projectId: 'astico-app',
    storageBucket: 'astico-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnWM_uHxIDexnKkhbtH0Fpzh4G4Bqczc',
    appId: '1:34606072539:ios:8fdc29340aa58b9662c2fe',
    messagingSenderId: '34606072539',
    projectId: 'astico-app',
    storageBucket: 'astico-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYnWM_uHxIDexnKkhbtH0Fpzh4G4Bqczc',
    appId: '1:34606072539:ios:8fdc29340aa58b9662c2fe',
    messagingSenderId: '34606072539',
    projectId: 'astico-app',
    storageBucket: 'astico-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpw5XEHcSPF-dvPMReaWksq69QPa6mrRA',
    appId: '1:34606072539:web:62818416e6c496b162c2fe',
    messagingSenderId: '34606072539',
    projectId: 'astico-app',
    authDomain: 'astico-app.firebaseapp.com',
    storageBucket: 'astico-app.firebasestorage.app',
    measurementId: 'G-Y8KNWCEVJP',
  );

}